# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: OrderService CI

on:
  push:
    branches: ["main"]
  pull_request:
    types: [closed]
    branches: ["main"]
    paths:
      - 'orderservice/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Build orderService
        run: |
          cd orderservice
          chmod +x gradlew
          ./gradlew clean build -x test

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle
      - name: Test orderService
        run: |
          cd orderservice
          chmod +x gradlew
          ./gradlew test
        

  code-analysis:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle
      - name: Spot bugs analysis
        run: |
          cd orderservice
          chmod +x gradlew
          ./gradlew spotbugsMain
        continue-on-error: true
      - name: Upload SpotBugs report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: spotbugs-report
          path: orderservice/build/reports/spotbugs/

  artifact-creation:
    runs-on: ubuntu-latest
    needs: [build, test, code-analysis]
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle
      - name: Build Jar
        run: |
          cd orderservice
          chmod +x gradlew
          ./gradlew clean build -x test

      - name: set up docker build
        uses: docker/setup-buildx-action@v3

      - name: build and push docker image
        uses: docker/build-push-action@v5
        with:
          context: ./orderservice
          push: false
          tags: orderservice:latest

      - name: upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: orderservice-jar
          path: orderservice/build/libs/orderservice-0.0.1-SNAPSHOT.jar

